## 인구 데이터 확보하고 정리하기

In [2]:
import pandas as pd
import numpy as np

import platform
import matplotlib.pyplot as plt

%matplotlib inline

from matplotlib import rc

if platform.system() == 'Darwin':
    rc('font', family='AppleGothic')
    
plt.rcParams['axes.unicode_minus'] = False

In [3]:
population = pd.read_excel('./population_raw_data.xlsx', header=1)
population.fillna(method='pad', inplace=True)

population.rename(columns = {'행정구역(동읍면)별(1)': '광역시도',
                            '행정구역(동읍면)별(2)': '시도',
                            '계': '인구수'}, inplace=True)

population = population[(population['시도'] != '소계')]

population

,광역시도,시도,항목,인구수,20 - 24세,25 - 29세,30 - 34세,35 - 39세,65 - 69세,70 - 74세,75 - 79세,80 - 84세,85 - 89세,90 - 94세,95 - 99세,100+
6,서울특별시,종로구,총인구수 (명),152737.0,11379.0,11891.0,10684,10379.0,7411.0,6636.0,5263,3104.0,1480.0,602.0,234,220.0
7,서울특별시,종로구,남자인구수 (명),75201.0,5620.0,6181.0,5387,5034.0,3411.0,3009.0,2311,1289.0,506.0,207.0,89,73.0
8,서울특별시,종로구,여자인구수 (명),77536.0,5759.0,5710.0,5297,5345.0,4000.0,3627.0,2952,1815.0,974.0,395.0,145,147.0
9,서울특별시,중구,총인구수 (명),125249.0,8216.0,9529.0,10332,10107.0,6399.0,5313.0,4127,2502.0,1260.0,469.0,158,160.0
10,서울특별시,중구,남자인구수 (명),62204.0,4142.0,4792.0,5192,5221.0,3113.0,2405.0,1752,929.0,414.0,132.0,56,51.0
11,서울특별시,중구,여자인구수 (명),63045.0,4074.0,4737.0,5140,4886.0,3286.0,2908.0,2375,1573.0,846.0,337.0,102,109.0
12,서울특별시,용산구,총인구수 (명),230241.0,14317.0,16972.0,19032,19127.0,10675.0,9093.0,7477,4553.0,2254.0,916.0,264,315.0
13,서울특별시,용산구,남자인구수 (명),111601.0,6937.0,8373.0,9455,9434.0,4834.0,3975.0,3094,1739.0,750.0,284.0,102,88.0
14,서울특별시,용산구,여자인구수 (명),118640.0,7380.0,8599.0,9577,9693.0,5841.0,5118.0,4383,2814.0,1504.0,632.0,162,227.0
15,서울특별시,성동구,총인구수 (명),299259.0,20813.0,23383.0,25507,25979.0,12938.0,10734.0,7989,4450.0,1944.0,678.0,209,198.0
16,서울특별시,성동구,남자인구수 (명),148326.0,10609.0,11848.0,12692,13154.0,6090.0,4863.0,3480,1698.0,580.0,184.0,56,54.0
17,서울특별시,성동구,여자인구수 (명),150933.0,10204.0,11535.0,12815,12825.0,6848.0,5871.0,4509,2752.0,1364.0,494.0,153,144.0
18,서울특별시,광진구,총인구수 (명),357215.0,27368.0,32092.0,32302,29496.0,14402.0,11300.0,8121,4349.0,2029.0,689.0,228,174.0
19,서울특별시,광진구,남자인구수 (명),174797.0,13317.0,15555.0,16034,14875.0,6775.0,5376.0,3693,1609.0,631.0,170.0,54,37.0
20,서울특별시,광진구,여자인구수 (명),182418.0,14051.0,16537.0,16268,14621.0,7627.0,5924.0,4428,2740.0,1398.0,519.0,174,137.0
21,서울특별시,동대문구,총인구수 (명),355069.0,26261.0,27808.0,27277,28095.0,17506.0,14867.0,11008,5926.0,2577.0,887.0,288,242.0
22,서울특별시,동대문구,남자인구수 (명),177640.0,13162.0,14859.0,14140,14489.0,8237.0,6815.0,4950,2375.0,801.0,248.0,87,68.0
23,서울특별시,동대문구,여자인구수 (명),177429.0,13099.0,12949.0,13137,13606.0,9269.0,8052.0,6058,3551.0,1776.0,639.0,201,174.0
24,서울특별시,중랑구,총인구수 (명),411005.0,28727.0,29833.0,32277,32632.0,19957.0,15415.0,10783,5784.0,2596.0,896.0,257,154.0
25,서울특별시,중랑구,남자인구수 (명),204900.0,14676.0,14784.0,16607,17248.0,9448.0,7189.0,4879,2214.0,667.0,211.0,57,37.0
26,서울특별시,중랑구,여자인구수 (명),206105.0,14051.0,15049.0,15670,15384.0,10509.0,8226.0,5904,3570.0,1929.0,685.0,200,117.0
27,서울특별시,성북구,총인구수 (명),450355.0,32372.0,32003.0,32154,35029.0,20618.0,17629.0,13312,7284.0,3279.0,1099.0,352,305.0
28,서울특별시,성북구,남자인구수 (명),219951.0,15761.0,16229.0,16075,17424.0,9402.0,7979.0,5825,2856.0,978.0,287.0,87,78.0
29,서울특별시,성북구,여자인구수 (명),230404.0,16611.0,15774.0,16079,17605.0,11216.0,9650.0,7487,4428.0,2301.0,812.0,265,227.0
30,서울특별시,강북구,총인구수 (명),327195.0,22058.0,21374.0,22650,24750.0,18172.0,15323.0,11103,5654.0,2373.0,842.0,256,241.0
31,서울특별시,강북구,남자인구수 (명),160861.0,11206.0,10737.0,11838,12998.0,8084.0,6836.0,4961,2313.0,731.0,219.0,66,63.0
32,서울특별시,강북구,여자인구수 (명),166334.0,10852.0,10637.0,10812,11752.0,10088.0,8487.0,6142,3341.0,1642.0,623.0,190,178.0
33,서울특별시,도봉구,총인구수 (명),348220.0,24350.0,22867.0,23613,25303.0,16819.0,13559.0,10265,5829.0,2696.0,938.0,231,129.0
34,서울특별시,도봉구,남자인구수 (명),171238.0,12666.0,11645.0,12255,12757.0,8073.0,6328.0,4547,2172.0,865.0,240.0,68,25.0
35,서울특별시,도봉구,여자인구수 (명),176982.0,11684.0,11222.0,11358,12546.0,8746.0,7231.0,5718,3657.0,1831.0,698.0,163,104.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813,경상남도,창녕군,총인구수 (명),63982.0,3279.0,2721.0,2863,3309.0,4498.0,3981.0,4202,2813.0,1261.0,321.0,54,19.0
814,경상남도,창녕군,남자인구수 (명),31735.0,1922.0,1591.0,1548,1820.0,2174.0,1639.0,1500,876.0,283.0,56.0,12,0.0
815,경상남도,창녕군,여자인구수 (명),32247.0,1357.0,1130.0,1315,1489.0,2324.0,2342.0,2702,1937.0,978.0,265.0,42,19.0
816,경상남도,고성군,총인구수 (명),54703.0,2672.0,1989.0,2582,3102.0,3828.0,3282.0,3268,2459.0,1179.0,363.0,66,17.0
817,경상남도,고성군,남자인구수 (명),27452.0,1538.0,1117.0,1442,1762.0,1880.0,1398.0,1222,804.0,282.0,63.0,13,3.0
818,경상남도,고성군,여자인구수 (명),27251.0,1134.0,872.0,1140,1340.0,1948.0,1884.0,2046,1655.0,897.0,300.0,53,14.0
819,경상남도,남해군,총인구수 (명),45129.0,2130.0,1454.0,1336,1727.0,3669.0,3356.0,3644,2816.0,1538.0,559.0,91,19.0
820,경상남도,남해군,남자인구수 (명),21566.0,1273.0,827.0,723,892.0,1753.0,1439.0,1358,874.0,361.0,88.0,12,0.0
821,경상남도,남해군,여자인구수 (명),23563.0,857.0,627.0,613,835.0,1916.0,1917.0,2286,1942.0,1177.0,471.0,79,19.0
822,경상남도,하동군,총인구수 (명),49622.0,2642.0,2006.0,1808,2118.0,3569.0,3239.0,3451,2464.0,1285.0,407.0,80,19.0
823,경상남도,하동군,남자인구수 (명),24463.0,1521.0,1152.0,975,1147.0,1698.0,1356.0,1266,765.0,337.0,81.0,18,2.0
824,경상남도,하동군,여자인구수 (명),25159.0,1121.0,854.0,833,971.0,1871.0,1883.0,2185,1699.0,948.0,326.0,62,17.0
825,경상남도,산청군,총인구수 (명),36098.0,1591.0,1249.0,1273,1448.0,2712.0,2652.0,2870,2059.0,953.0,314.0,63,15.0
826,경상남도,산청군,남자인구수 (명),17666.0,907.0,689.0,681,823.0,1370.0,1085.0,1031,642.0,249.0,69.0,10,2.0
827,경상남도,산청군,여자인구수 (명),18432.0,684.0,560.0,592,625.0,1342.0,1567.0,1839,1417.0,704.0,245.0,53,13.0
828,경상남도,함양군,총인구수 (명),40241.0,1943.0,1332.0,1453,1792.0,2869.0,2712.0,3124,2063.0,1050.0,360.0,64,32.0
829,경상남도,함양군,남자인구수 (명),19244.0,1077.0,717.0,765,939.0,1321.0,1041.0,1197,617.0,248.0,96.0,10,8.0
830,경상남도,함양군,여자인구수 (명),20997.0,866.0,615.0,688,853.0,1548.0,1671.0,1927,1446.0,802.0,264.0,54,24.0
831,경상남도,거창군,총인구수 (명),63308.0,3701.0,2478.0,2677,3277.0,3792.0,3493.0,3815,2682.0,1269.0,416.0,98,26.0
832,경상남도,거창군,남자인구수 (명),30746.0,2108.0,1399.0,1379,1638.0,1731.0,1394.0,1448,865.0,358.0,91.0,22,7.0
833,경상남도,거창군,여자인구수 (명),32562.0,1593.0,1079.0,1298,1639.0,2061.0,2099.0,2367,1817.0,911.0,325.0,76,19.0
834,경상남도,합천군,총인구수 (명),48026.0,2057.0,1540.0,1638,1943.0,3891.0,3717.0,4349,3142.0,1346.0,409.0,90,28.0
835,경상남도,합천군,남자인구수 (명),22825.0,1179.0,878.0,881,1060.0,1812.0,1484.0,1526,938.0,356.0,80.0,14,2.0
836,경상남도,합천군,여자인구수 (명),25201.0,878.0,662.0,757,883.0,2079.0,2233.0,2823,2204.0,990.0,329.0,76,26.0
840,제주특별자치도,제주시,총인구수 (명),470665.0,32638.0,25363.0,29771,36412.0,17739.0,14659.0,12119,8386.0,3976.0,1613.0,513,154.0
841,제주특별자치도,제주시,남자인구수 (명),235977.0,17377.0,13118.0,15084,18350.0,8474.0,6782.0,4941,2737.0,854.0,226.0,53,17.0
842,제주특별자치도,제주시,여자인구수 (명),234688.0,15261.0,12245.0,14687,18062.0,9265.0,7877.0,7178,5649.0,3122.0,1387.0,460,137.0
843,제주특별자치도,서귀포시,총인구수 (명),170932.0,10505.0,8067.0,9120,11606.0,8686.0,7460.0,6456,4521.0,1855.0,733.0,242,77.0
844,제주특별자치도,서귀포시,남자인구수 (명),86568.0,5600.0,4247.0,4693,6082.0,4237.0,3441.0,2611,1494.0,370.0,103.0,29,9.0
845,제주특별자치도,서귀포시,여자인구수 (명),84364.0,4905.0,3820.0,4427,5524.0,4449.0,4019.0,3845,3027.0,1485.0,630.0,213,68.0

In [4]:
population.is_copy = False

population.rename(columns = {'항목': '구분'}, inplace=True)

population.loc[population['구분'] =='총인구수 (명)', '구분'] = '합계'
population.loc[population['구분'] =='남자인구수 (명)', '구분'] = '남자'
population.loc[population['구분'] =='여자인구수 (명)', '구분'] = '여자'

population

/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:5192: FutureWarning: Attribute 'is_copy' is deprecated and will be removed in a future version.
  object.__getattribute__(self, name)
/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:5193: FutureWarning: Attribute 'is_copy' is deprecated and will be removed in a future version.
  return object.__setattr__(self, name, value)

,광역시도,시도,구분,인구수,20 - 24세,25 - 29세,30 - 34세,35 - 39세,65 - 69세,70 - 74세,75 - 79세,80 - 84세,85 - 89세,90 - 94세,95 - 99세,100+
6,서울특별시,종로구,합계,152737.0,11379.0,11891.0,10684,10379.0,7411.0,6636.0,5263,3104.0,1480.0,602.0,234,220.0
7,서울특별시,종로구,남자,75201.0,5620.0,6181.0,5387,5034.0,3411.0,3009.0,2311,1289.0,506.0,207.0,89,73.0
8,서울특별시,종로구,여자,77536.0,5759.0,5710.0,5297,5345.0,4000.0,3627.0,2952,1815.0,974.0,395.0,145,147.0
9,서울특별시,중구,합계,125249.0,8216.0,9529.0,10332,10107.0,6399.0,5313.0,4127,2502.0,1260.0,469.0,158,160.0
10,서울특별시,중구,남자,62204.0,4142.0,4792.0,5192,5221.0,3113.0,2405.0,1752,929.0,414.0,132.0,56,51.0
11,서울특별시,중구,여자,63045.0,4074.0,4737.0,5140,4886.0,3286.0,2908.0,2375,1573.0,846.0,337.0,102,109.0
12,서울특별시,용산구,합계,230241.0,14317.0,16972.0,19032,19127.0,10675.0,9093.0,7477,4553.0,2254.0,916.0,264,315.0
13,서울특별시,용산구,남자,111601.0,6937.0,8373.0,9455,9434.0,4834.0,3975.0,3094,1739.0,750.0,284.0,102,88.0
14,서울특별시,용산구,여자,118640.0,7380.0,8599.0,9577,9693.0,5841.0,5118.0,4383,2814.0,1504.0,632.0,162,227.0
15,서울특별시,성동구,합계,299259.0,20813.0,23383.0,25507,25979.0,12938.0,10734.0,7989,4450.0,1944.0,678.0,209,198.0
16,서울특별시,성동구,남자,148326.0,10609.0,11848.0,12692,13154.0,6090.0,4863.0,3480,1698.0,580.0,184.0,56,54.0
17,서울특별시,성동구,여자,150933.0,10204.0,11535.0,12815,12825.0,6848.0,5871.0,4509,2752.0,1364.0,494.0,153,144.0
18,서울특별시,광진구,합계,357215.0,27368.0,32092.0,32302,29496.0,14402.0,11300.0,8121,4349.0,2029.0,689.0,228,174.0
19,서울특별시,광진구,남자,174797.0,13317.0,15555.0,16034,14875.0,6775.0,5376.0,3693,1609.0,631.0,170.0,54,37.0
20,서울특별시,광진구,여자,182418.0,14051.0,16537.0,16268,14621.0,7627.0,5924.0,4428,2740.0,1398.0,519.0,174,137.0
21,서울특별시,동대문구,합계,355069.0,26261.0,27808.0,27277,28095.0,17506.0,14867.0,11008,5926.0,2577.0,887.0,288,242.0
22,서울특별시,동대문구,남자,177640.0,13162.0,14859.0,14140,14489.0,8237.0,6815.0,4950,2375.0,801.0,248.0,87,68.0
23,서울특별시,동대문구,여자,177429.0,13099.0,12949.0,13137,13606.0,9269.0,8052.0,6058,3551.0,1776.0,639.0,201,174.0
24,서울특별시,중랑구,합계,411005.0,28727.0,29833.0,32277,32632.0,19957.0,15415.0,10783,5784.0,2596.0,896.0,257,154.0
25,서울특별시,중랑구,남자,204900.0,14676.0,14784.0,16607,17248.0,9448.0,7189.0,4879,2214.0,667.0,211.0,57,37.0
26,서울특별시,중랑구,여자,206105.0,14051.0,15049.0,15670,15384.0,10509.0,8226.0,5904,3570.0,1929.0,685.0,200,117.0
27,서울특별시,성북구,합계,450355.0,32372.0,32003.0,32154,35029.0,20618.0,17629.0,13312,7284.0,3279.0,1099.0,352,305.0
28,서울특별시,성북구,남자,219951.0,15761.0,16229.0,16075,17424.0,9402.0,7979.0,5825,2856.0,978.0,287.0,87,78.0
29,서울특별시,성북구,여자,230404.0,16611.0,15774.0,16079,17605.0,11216.0,9650.0,7487,4428.0,2301.0,812.0,265,227.0
30,서울특별시,강북구,합계,327195.0,22058.0,21374.0,22650,24750.0,18172.0,15323.0,11103,5654.0,2373.0,842.0,256,241.0
31,서울특별시,강북구,남자,160861.0,11206.0,10737.0,11838,12998.0,8084.0,6836.0,4961,2313.0,731.0,219.0,66,63.0
32,서울특별시,강북구,여자,166334.0,10852.0,10637.0,10812,11752.0,10088.0,8487.0,6142,3341.0,1642.0,623.0,190,178.0
33,서울특별시,도봉구,합계,348220.0,24350.0,22867.0,23613,25303.0,16819.0,13559.0,10265,5829.0,2696.0,938.0,231,129.0
34,서울특별시,도봉구,남자,171238.0,12666.0,11645.0,12255,12757.0,8073.0,6328.0,4547,2172.0,865.0,240.0,68,25.0
35,서울특별시,도봉구,여자,176982.0,11684.0,11222.0,11358,12546.0,8746.0,7231.0,5718,3657.0,1831.0,698.0,163,104.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813,경상남도,창녕군,합계,63982.0,3279.0,2721.0,2863,3309.0,4498.0,3981.0,4202,2813.0,1261.0,321.0,54,19.0
814,경상남도,창녕군,남자,31735.0,1922.0,1591.0,1548,1820.0,2174.0,1639.0,1500,876.0,283.0,56.0,12,0.0
815,경상남도,창녕군,여자,32247.0,1357.0,1130.0,1315,1489.0,2324.0,2342.0,2702,1937.0,978.0,265.0,42,19.0
816,경상남도,고성군,합계,54703.0,2672.0,1989.0,2582,3102.0,3828.0,3282.0,3268,2459.0,1179.0,363.0,66,17.0
817,경상남도,고성군,남자,27452.0,1538.0,1117.0,1442,1762.0,1880.0,1398.0,1222,804.0,282.0,63.0,13,3.0
818,경상남도,고성군,여자,27251.0,1134.0,872.0,1140,1340.0,1948.0,1884.0,2046,1655.0,897.0,300.0,53,14.0
819,경상남도,남해군,합계,45129.0,2130.0,1454.0,1336,1727.0,3669.0,3356.0,3644,2816.0,1538.0,559.0,91,19.0
820,경상남도,남해군,남자,21566.0,1273.0,827.0,723,892.0,1753.0,1439.0,1358,874.0,361.0,88.0,12,0.0
821,경상남도,남해군,여자,23563.0,857.0,627.0,613,835.0,1916.0,1917.0,2286,1942.0,1177.0,471.0,79,19.0
822,경상남도,하동군,합계,49622.0,2642.0,2006.0,1808,2118.0,3569.0,3239.0,3451,2464.0,1285.0,407.0,80,19.0
823,경상남도,하동군,남자,24463.0,1521.0,1152.0,975,1147.0,1698.0,1356.0,1266,765.0,337.0,81.0,18,2.0
824,경상남도,하동군,여자,25159.0,1121.0,854.0,833,971.0,1871.0,1883.0,2185,1699.0,948.0,326.0,62,17.0
825,경상남도,산청군,합계,36098.0,1591.0,1249.0,1273,1448.0,2712.0,2652.0,2870,2059.0,953.0,314.0,63,15.0
826,경상남도,산청군,남자,17666.0,907.0,689.0,681,823.0,1370.0,1085.0,1031,642.0,249.0,69.0,10,2.0
827,경상남도,산청군,여자,18432.0,684.0,560.0,592,625.0,1342.0,1567.0,1839,1417.0,704.0,245.0,53,13.0
828,경상남도,함양군,합계,40241.0,1943.0,1332.0,1453,1792.0,2869.0,2712.0,3124,2063.0,1050.0,360.0,64,32.0
829,경상남도,함양군,남자,19244.0,1077.0,717.0,765,939.0,1321.0,1041.0,1197,617.0,248.0,96.0,10,8.0
830,경상남도,함양군,여자,20997.0,866.0,615.0,688,853.0,1548.0,1671.0,1927,1446.0,802.0,264.0,54,24.0
831,경상남도,거창군,합계,63308.0,3701.0,2478.0,2677,3277.0,3792.0,3493.0,3815,2682.0,1269.0,416.0,98,26.0
832,경상남도,거창군,남자,30746.0,2108.0,1399.0,1379,1638.0,1731.0,1394.0,1448,865.0,358.0,91.0,22,7.0
833,경상남도,거창군,여자,32562.0,1593.0,1079.0,1298,1639.0,2061.0,2099.0,2367,1817.0,911.0,325.0,76,19.0
834,경상남도,합천군,합계,48026.0,2057.0,1540.0,1638,1943.0,3891.0,3717.0,4349,3142.0,1346.0,409.0,90,28.0
835,경상남도,합천군,남자,22825.0,1179.0,878.0,881,1060.0,1812.0,1484.0,1526,938.0,356.0,80.0,14,2.0
836,경상남도,합천군,여자,25201.0,878.0,662.0,757,883.0,2079.0,2233.0,2823,2204.0,990.0,329.0,76,26.0
840,제주특별자치도,제주시,합계,470665.0,32638.0,25363.0,29771,36412.0,17739.0,14659.0,12119,8386.0,3976.0,1613.0,513,154.0
841,제주특별자치도,제주시,남자,235977.0,17377.0,13118.0,15084,18350.0,8474.0,6782.0,4941,2737.0,854.0,226.0,53,17.0
842,제주특별자치도,제주시,여자,234688.0,15261.0,12245.0,14687,18062.0,9265.0,7877.0,7178,5649.0,3122.0,1387.0,460,137.0
843,제주특별자치도,서귀포시,합계,170932.0,10505.0,8067.0,9120,11606.0,8686.0,7460.0,6456,4521.0,1855.0,733.0,242,77.0
844,제주특별자치도,서귀포시,남자,86568.0,5600.0,4247.0,4693,6082.0,4237.0,3441.0,2611,1494.0,370.0,103.0,29,9.0
845,제주특별자치도,서귀포시,여자,84364.0,4905.0,3820.0,4427,5524.0,4449.0,4019.0,3845,3027.0,1485.0,630.0,213,68.0

## 인구 소멸 위기 지역 계산하고 데이터 정리하기

In [8]:
population['20-39세'] = population['20 - 24세'] + population['25 - 29세'] + population['30 - 34세'] + population['35 - 39세']
population['65세이상'] = population['65 - 69세'] + population['70 - 74세'] + population['75 - 79세'] + population['80 - 84세'] + population['85 - 89세'] + population['90 - 94세'] + population['95 - 99세'] + population['100+']

population.head(10)

,광역시도,시도,구분,인구수,20 - 24세,25 - 29세,30 - 34세,35 - 39세,65 - 69세,70 - 74세,75 - 79세,80 - 84세,85 - 89세,90 - 94세,95 - 99세,100+,20세-39세,65세 이상,65세이상,20-39세
6,서울특별시,종로구,합계,152737.0,11379.0,11891.0,10684,10379.0,7411.0,6636.0,5263,3104.0,1480.0,602.0,234,220.0,44333.0,24950.0,24950.0,44333.0
7,서울특별시,종로구,남자,75201.0,5620.0,6181.0,5387,5034.0,3411.0,3009.0,2311,1289.0,506.0,207.0,89,73.0,22222.0,10895.0,10895.0,22222.0
8,서울특별시,종로구,여자,77536.0,5759.0,5710.0,5297,5345.0,4000.0,3627.0,2952,1815.0,974.0,395.0,145,147.0,22111.0,14055.0,14055.0,22111.0
9,서울특별시,중구,합계,125249.0,8216.0,9529.0,10332,10107.0,6399.0,5313.0,4127,2502.0,1260.0,469.0,158,160.0,38184.0,20388.0,20388.0,38184.0
10,서울특별시,중구,남자,62204.0,4142.0,4792.0,5192,5221.0,3113.0,2405.0,1752,929.0,414.0,132.0,56,51.0,19347.0,8852.0,8852.0,19347.0
11,서울특별시,중구,여자,63045.0,4074.0,4737.0,5140,4886.0,3286.0,2908.0,2375,1573.0,846.0,337.0,102,109.0,18837.0,11536.0,11536.0,18837.0
12,서울특별시,용산구,합계,230241.0,14317.0,16972.0,19032,19127.0,10675.0,9093.0,7477,4553.0,2254.0,916.0,264,315.0,69448.0,35547.0,35547.0,69448.0
13,서울특별시,용산구,남자,111601.0,6937.0,8373.0,9455,9434.0,4834.0,3975.0,3094,1739.0,750.0,284.0,102,88.0,34199.0,14866.0,14866.0,34199.0
14,서울특별시,용산구,여자,118640.0,7380.0,8599.0,9577,9693.0,5841.0,5118.0,4383,2814.0,1504.0,632.0,162,227.0,35249.0,20681.0,20681.0,35249.0
15,서울특별시,성동구,합계,299259.0,20813.0,23383.0,25507,25979.0,12938.0,10734.0,7989,4450.0,1944.0,678.0,209,198.0,95682.0,39140.0,39140.0,95682.0

In [10]:
pop = pd.pivot_table(population,
                    index=['광역시도', '시도'],
                    columns=['구분'],
                    values=['인구수', '20-39세', '65세이상'])
pop

            20-39세                        65세이상                         인구수  \
구분              남자        여자        합계       남자       여자       합계        남자
광역시도 시도
강원도  강릉시   26286.0   23098.0   49384.0  15767.0  21912.0  37679.0  106231.0
     고성군    4494.0    2529.0    7023.0   2900.0   4251.0   7151.0   15899.0
     동해시   11511.0    9753.0   21264.0   6392.0   8732.0  15124.0   47166.0
     삼척시    8708.0    7115.0   15823.0   5892.0   8718.0  14610.0   35253.0
     속초시    9956.0    8752.0   18708.0   5139.0   7613.0  12752.0   40288.0
...            ...       ...       ...      ...      ...      ...       ...
충청북도 진천군    9391.0    7622.0   17013.0   4731.0   6575.0  11306.0   36387.0
     청원구   32216.0   27805.0   60021.0   8417.0  11914.0  20331.0   97006.0
     청주시  128318.0  115719.0  244037.0  37882.0  53671.0  91553.0  419323.0
     충주시   26600.0   22757.0   49357.0  14407.0  20383.0  34790.0  104877.0
     흥덕구   40933.0   37675.0   78608.0   9788.0  13671.0  23459.0  127647.0


구분              여자        합계
광역시도 시도
강원도  강릉시  107615.0  213846.0
     고성군   14215.0   30114.0
     동해시   46131.0   93297.0
     삼척시   34346.0   69599.0
     속초시   41505.0   81793.0
...            ...       ...
충청북도 진천군   33563.0   69950.0
     청원구   93807.0  190813.0
     청주시  415874.0  835197.0
     충주시  103473.0  208350.0
     흥덕구  125916.0  253563.0

[264 rows x 9 columns]

In [11]:
pop['소멸비율'] = pop['20-39세','여자'] / (pop['65세이상','합계'] / 2)
pop.head()

           20-39세                      65세이상                         인구수  \
구분             남자       여자       합계       남자       여자       합계        남자
광역시도 시도
강원도  강릉시  26286.0  23098.0  49384.0  15767.0  21912.0  37679.0  106231.0
     고성군   4494.0   2529.0   7023.0   2900.0   4251.0   7151.0   15899.0
     동해시  11511.0   9753.0  21264.0   6392.0   8732.0  15124.0   47166.0
     삼척시   8708.0   7115.0  15823.0   5892.0   8718.0  14610.0   35253.0
     속초시   9956.0   8752.0  18708.0   5139.0   7613.0  12752.0   40288.0

                                  소멸비율
구분              여자        합계
광역시도 시도
강원도  강릉시  107615.0  213846.0  1.226041
     고성군   14215.0   30114.0  0.707314
     동해시   46131.0   93297.0  1.289738
     삼척시   34346.0   69599.0  0.973990
     속초시   41505.0   81793.0  1.372647

In [12]:
pop['소멸위기지역'] = pop['소멸비율'] < 1.0
pop.head()

           20-39세                      65세이상                         인구수  \
구분             남자       여자       합계       남자       여자       합계        남자
광역시도 시도
강원도  강릉시  26286.0  23098.0  49384.0  15767.0  21912.0  37679.0  106231.0
     고성군   4494.0   2529.0   7023.0   2900.0   4251.0   7151.0   15899.0
     동해시  11511.0   9753.0  21264.0   6392.0   8732.0  15124.0   47166.0
     삼척시   8708.0   7115.0  15823.0   5892.0   8718.0  14610.0   35253.0
     속초시   9956.0   8752.0  18708.0   5139.0   7613.0  12752.0   40288.0

                                  소멸비율 소멸위기지역
구분              여자        합계
광역시도 시도
강원도  강릉시  107615.0  213846.0  1.226041  False
     고성군   14215.0   30114.0  0.707314   True
     동해시   46131.0   93297.0  1.289738  False
     삼척시   34346.0   69599.0  0.973990   True
     속초시   41505.0   81793.0  1.372647  False

In [13]:
pop[pop['소멸위기지역'] == True].index.get_level_values(1)

Index(['고성군', '삼척시', '양양군', '영월군', '정선군', '평창군', '홍천군', '횡성군', '가평군', '양평군',
       '연천군', '거창군', '고성군', '남해군', '밀양시', '산청군', '의령군', '창녕군', '하동군', '함안군',
       '함양군', '합천군', '고령군', '군위군', '문경시', '봉화군', '상주시', '성주군', '영덕군', '영양군',
       '영주시', '영천시', '예천군', '울릉군', '울진군', '의성군', '청도군', '청송군', '동구', '영도구',
       '강화군', '옹진군', '강진군', '고흥군', '곡성군', '구례군', '담양군', '보성군', '신안군', '영광군',
       '영암군', '완도군', '장성군', '장흥군', '진도군', '함평군', '해남군', '화순군', '고창군', '김제시',
       '남원시', '무주군', '부안군', '순창군', '임실군', '장수군', '정읍시', '진안군', '공주시', '금산군',
       '논산시', '보령시', '부여군', '서천군', '예산군', '청양군', '태안군', '홍성군', '괴산군', '단양군',
       '보은군', '영동군', '옥천군'],
      dtype='object', name='시도')

In [14]:
pop.reset_index(inplace=True)
pop.head()

   광역시도   시도   20-39세                      65세이상                         인구수  \
구분                 남자       여자       합계       남자       여자       합계        남자
0   강원도  강릉시  26286.0  23098.0  49384.0  15767.0  21912.0  37679.0  106231.0
1   강원도  고성군   4494.0   2529.0   7023.0   2900.0   4251.0   7151.0   15899.0
2   강원도  동해시  11511.0   9753.0  21264.0   6392.0   8732.0  15124.0   47166.0
3   강원도  삼척시   8708.0   7115.0  15823.0   5892.0   8718.0  14610.0   35253.0
4   강원도  속초시   9956.0   8752.0  18708.0   5139.0   7613.0  12752.0   40288.0

                            소멸비율 소멸위기지역
구분        여자        합계
0   107615.0  213846.0  1.226041  False
1    14215.0   30114.0  0.707314   True
2    46131.0   93297.0  1.289738  False
3    34346.0   69599.0  0.973990   True
4    41505.0   81793.0  1.372647  False

In [15]:
tmp_columns = [pop.columns.get_level_values(0)[n] + pop.columns.get_level_values(1)[n] 
               for n in range(0, len(pop.columns.get_level_values(0)))]
pop.columns = tmp_columns

pop.head()

,광역시도,시도,20-39세남자,20-39세여자,20-39세합계,65세이상남자,65세이상여자,65세이상합계,인구수남자,인구수여자,인구수합계,소멸비율,소멸위기지역
0,강원도,강릉시,26286.0,23098.0,49384.0,15767.0,21912.0,37679.0,106231.0,107615.0,213846.0,1.226041,False
1,강원도,고성군,4494.0,2529.0,7023.0,2900.0,4251.0,7151.0,15899.0,14215.0,30114.0,0.707314,True
2,강원도,동해시,11511.0,9753.0,21264.0,6392.0,8732.0,15124.0,47166.0,46131.0,93297.0,1.289738,False
3,강원도,삼척시,8708.0,7115.0,15823.0,5892.0,8718.0,14610.0,35253.0,34346.0,69599.0,0.973990,True
4,강원도,속초시,9956.0,8752.0,18708.0,5139.0,7613.0,12752.0,40288.0,41505.0,81793.0,1.372647,False

In [16]:
pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264 entries, 0 to 263
Data columns (total 13 columns):
광역시도        264 non-null object
시도          264 non-null object
20-39세남자    264 non-null float64
20-39세여자    264 non-null float64
20-39세합계    264 non-null float64
65세이상남자     264 non-null float64
65세이상여자     264 non-null float64
65세이상합계     264 non-null float64
인구수남자       264 non-null float64
인구수여자       264 non-null float64
인구수합계       264 non-null float64
소멸비율        264 non-null float64
소멸위기지역      264 non-null bool
dtypes: bool(1), float64(10), object(2)
memory usage: 25.1+ KB